### ISSUE TITLE
`wf2.yaml` config file

### ISSUE THREAD

**Issue by shakyShane** [WeareJH/wf2#14]
whilst the goal is `zero config` - there's some things that are unavoidable.

- domain
- php version
- dir of theme (for npm commands)

We'll leave this open to be extended, but for now these seem enough

```yaml
recipe: m2

# Will accept a comma separated list
domain: local.m2

# Will be 7.2 by default
php: 7.1

# Needed for the npm command
theme_dir: app/design/frontend/Trend/default
```
